### ISSUE TITLE
Failed to load the rust-doc-viewer package

### ISSUE THREAD

**Issue by sbalousek** [surrsurus/atom-rust-doc-viewer#1]
[Enter steps to reproduce:]

1. Install "atom-rust-doc-viewer" package

**Atom**: 1.15.0 x64
**Electron**: 1.4.15
**OS**: "Arch Linux"
**Thrown From**: [rust-doc-viewer](https://github.com/surrsurus/atom-rust-doc-viewer) package 2.5.2

### Stack Trace

Failed to load the rust-doc-viewer package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/lib/atom/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:50:27)
    at /packages/rust-doc-viewer/lib/rust-doc-viewer-view.coffee:3:25)
    at /packages/rust-doc-viewer/lib/rust-doc-viewer-view.coffee:1:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:109:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:50:27)
    at /packages/rust-doc-viewer/lib/rust-doc-viewer.coffee:7:17)
    at /packages/rust-doc-viewer/lib/rust-doc-viewer.coffee:2:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:109:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/lib/atom/src/package.js:796:27)
    at /usr/lib/atom/src/package.js:123:28
    at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:96:15)
    at Package.module.exports.Package.load (/usr/lib/atom/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/lib/atom/src/package-manager.js:460:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:540:30)
    at /usr/lib/atom/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/usr/lib/atom/src/buffered-process.js:322:11)
    at /usr/lib/atom/src/buffered-process.js:343:11
    at Socket.<anonymous> (/usr/lib/atom/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -4:19.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
     -4:12.9.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:28.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.29.17 
atomic-emacs 0.10.0 
autohide-tree-view 0.25.1 
busy-signal 1.3.0 
comment-dwim-light 0.9.6 
file-icons 2.1.2 
git-plus 7.3.3 
Hydrogen 1.10.1 
intentions 1.1.2 
json-colorer 1.0.0 
language-cmake 0.3.0 
language-prolog 0.10.0 
language-rust 0.4.10 
linter 2.1.2 
linter-cppcheck 0.2.3 
linter-json-lint 0.1.1 
linter-prolog 0.2.0 
linter-rust 0.8.0 
linter-ui-default 1.2.2 
pretty-json 1.6.3 
racer 0.20.0 
rust-api-docs-helper 0.5.1 
rust-doc-viewer 2.5.2 
tree-ignore 0.6.2 
tree-view-git-status 1.3.1 
```

**Comment by surrsurus** [comment]
The `atom-space-pen-views` package is bundled with Atom, so this could be a problem with a manual install. Try reinstalling the package, or enabling the part of atom that may have disabled `atom-space-pen-views` although I can't imagine that atom would allow it to be disabled.

**Comment by surrsurus** [comment]
I looked into it and there was a problem with the dependencies, it should be working properly now. Make sure to download the latest version, though atom should let you know there is an update available.

**Comment by surrsurus** [comment]
This issue should be fixed now, so I'll close the issue. If you continue to have problems, just make a new comment and I'll re-open it.
